version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      TZ: "Asia/Seoul"

